// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_defs.proto

package photo.img;

public final class ImageDefs {
  private ImageDefs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code photo.img.ImageFormat}
   */
  public enum ImageFormat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IF_JPEG = 0;</code>
     */
    IF_JPEG(0, 0),
    /**
     * <code>IF_PNG = 1;</code>
     */
    IF_PNG(1, 1),
    /**
     * <code>IF_GIF = 2;</code>
     */
    IF_GIF(2, 2),
    /**
     * <code>IF_UNKNOWN = 3;</code>
     */
    IF_UNKNOWN(3, 3),
    /**
     * <code>IF_ICO = 4;</code>
     */
    IF_ICO(4, 4),
    /**
     * <code>IF_BMP = 5;</code>
     */
    IF_BMP(5, 5),
    /**
     * <code>IF_WEBP = 6;</code>
     */
    IF_WEBP(6, 6),
    /**
     * <code>IF_SVG = 7;</code>
     */
    IF_SVG(7, 7),
    ;

    /**
     * <code>IF_JPEG = 0;</code>
     */
    public static final int IF_JPEG_VALUE = 0;
    /**
     * <code>IF_PNG = 1;</code>
     */
    public static final int IF_PNG_VALUE = 1;
    /**
     * <code>IF_GIF = 2;</code>
     */
    public static final int IF_GIF_VALUE = 2;
    /**
     * <code>IF_UNKNOWN = 3;</code>
     */
    public static final int IF_UNKNOWN_VALUE = 3;
    /**
     * <code>IF_ICO = 4;</code>
     */
    public static final int IF_ICO_VALUE = 4;
    /**
     * <code>IF_BMP = 5;</code>
     */
    public static final int IF_BMP_VALUE = 5;
    /**
     * <code>IF_WEBP = 6;</code>
     */
    public static final int IF_WEBP_VALUE = 6;
    /**
     * <code>IF_SVG = 7;</code>
     */
    public static final int IF_SVG_VALUE = 7;


    public final int getNumber() { return value; }

    public static ImageFormat valueOf(int value) {
      switch (value) {
        case 0: return IF_JPEG;
        case 1: return IF_PNG;
        case 2: return IF_GIF;
        case 3: return IF_UNKNOWN;
        case 4: return IF_ICO;
        case 5: return IF_BMP;
        case 6: return IF_WEBP;
        case 7: return IF_SVG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ImageFormat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ImageFormat>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ImageFormat>() {
            public ImageFormat findValueByNumber(int number) {
              return ImageFormat.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return photo.img.ImageDefs.getDescriptor().getEnumTypes().get(0);
    }

    private static final ImageFormat[] VALUES = values();

    public static ImageFormat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ImageFormat(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:photo.img.ImageFormat)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020image_defs.proto\022\tphoto.img*s\n\013ImageFo" +
      "rmat\022\013\n\007IF_JPEG\020\000\022\n\n\006IF_PNG\020\001\022\n\n\006IF_GIF\020" +
      "\002\022\016\n\nIF_UNKNOWN\020\003\022\n\n\006IF_ICO\020\004\022\n\n\006IF_BMP\020" +
      "\005\022\013\n\007IF_WEBP\020\006\022\n\n\006IF_SVG\020\007B\013B\tImageDefs"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
