// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: big.proto

package photo.bki;

public final class ImageBki {
  private ImageBki() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code photo.bki.SocNet}
   */
  public enum SocNet
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0, 0),
    /**
     * <code>VK = 1;</code>
     */
    VK(1, 1),
    /**
     * <code>MM = 2;</code>
     */
    MM(2, 2),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>VK = 1;</code>
     */
    public static final int VK_VALUE = 1;
    /**
     * <code>MM = 2;</code>
     */
    public static final int MM_VALUE = 2;


    public final int getNumber() { return value; }

    public static SocNet valueOf(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return VK;
        case 2: return MM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SocNet>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SocNet>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SocNet>() {
            public SocNet findValueByNumber(int number) {
              return SocNet.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return photo.bki.ImageBki.getDescriptor().getEnumTypes().get(0);
    }

    private static final SocNet[] VALUES = values();

    public static SocNet valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SocNet(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:photo.bki.SocNet)
  }

  public interface ImageIdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 imageHash = 1;
    /**
     * <code>required uint64 imageHash = 1;</code>
     */
    boolean hasImageHash();
    /**
     * <code>required uint64 imageHash = 1;</code>
     */
    long getImageHash();
  }
  /**
   * Protobuf type {@code photo.bki.ImageId}
   */
  public static final class ImageId extends
      com.google.protobuf.GeneratedMessage
      implements ImageIdOrBuilder {
    // Use ImageId.newBuilder() to construct.
    private ImageId(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ImageId(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ImageId defaultInstance;
    public static ImageId getDefaultInstance() {
      return defaultInstance;
    }

    public ImageId getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ImageId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              imageHash_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return photo.bki.ImageBki.internal_static_photo_bki_ImageId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return photo.bki.ImageBki.internal_static_photo_bki_ImageId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              photo.bki.ImageBki.ImageId.class, photo.bki.ImageBki.ImageId.Builder.class);
    }

    public static com.google.protobuf.Parser<ImageId> PARSER =
        new com.google.protobuf.AbstractParser<ImageId>() {
      public ImageId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageId(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ImageId> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 imageHash = 1;
    public static final int IMAGEHASH_FIELD_NUMBER = 1;
    private long imageHash_;
    /**
     * <code>required uint64 imageHash = 1;</code>
     */
    public boolean hasImageHash() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 imageHash = 1;</code>
     */
    public long getImageHash() {
      return imageHash_;
    }

    private void initFields() {
      imageHash_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasImageHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, imageHash_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, imageHash_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static photo.bki.ImageBki.ImageId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static photo.bki.ImageBki.ImageId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static photo.bki.ImageBki.ImageId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static photo.bki.ImageBki.ImageId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static photo.bki.ImageBki.ImageId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static photo.bki.ImageBki.ImageId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(photo.bki.ImageBki.ImageId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code photo.bki.ImageId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements photo.bki.ImageBki.ImageIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return photo.bki.ImageBki.internal_static_photo_bki_ImageId_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return photo.bki.ImageBki.internal_static_photo_bki_ImageId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                photo.bki.ImageBki.ImageId.class, photo.bki.ImageBki.ImageId.Builder.class);
      }

      // Construct using photo.bki.ImageBki.ImageId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        imageHash_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return photo.bki.ImageBki.internal_static_photo_bki_ImageId_descriptor;
      }

      public photo.bki.ImageBki.ImageId getDefaultInstanceForType() {
        return photo.bki.ImageBki.ImageId.getDefaultInstance();
      }

      public photo.bki.ImageBki.ImageId build() {
        photo.bki.ImageBki.ImageId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public photo.bki.ImageBki.ImageId buildPartial() {
        photo.bki.ImageBki.ImageId result = new photo.bki.ImageBki.ImageId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.imageHash_ = imageHash_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof photo.bki.ImageBki.ImageId) {
          return mergeFrom((photo.bki.ImageBki.ImageId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(photo.bki.ImageBki.ImageId other) {
        if (other == photo.bki.ImageBki.ImageId.getDefaultInstance()) return this;
        if (other.hasImageHash()) {
          setImageHash(other.getImageHash());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasImageHash()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        photo.bki.ImageBki.ImageId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (photo.bki.ImageBki.ImageId) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 imageHash = 1;
      private long imageHash_ ;
      /**
       * <code>required uint64 imageHash = 1;</code>
       */
      public boolean hasImageHash() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 imageHash = 1;</code>
       */
      public long getImageHash() {
        return imageHash_;
      }
      /**
       * <code>required uint64 imageHash = 1;</code>
       */
      public Builder setImageHash(long value) {
        bitField0_ |= 0x00000001;
        imageHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 imageHash = 1;</code>
       */
      public Builder clearImageHash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        imageHash_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:photo.bki.ImageId)
    }

    static {
      defaultInstance = new ImageId(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:photo.bki.ImageId)
  }

  public interface ImageStructOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string fullUrl = 1;
    /**
     * <code>required string fullUrl = 1;</code>
     */
    boolean hasFullUrl();
    /**
     * <code>required string fullUrl = 1;</code>
     */
    java.lang.String getFullUrl();
    /**
     * <code>required string fullUrl = 1;</code>
     */
    com.google.protobuf.ByteString
        getFullUrlBytes();

    // required uint32 width = 2;
    /**
     * <code>required uint32 width = 2;</code>
     */
    boolean hasWidth();
    /**
     * <code>required uint32 width = 2;</code>
     */
    int getWidth();

    // required uint32 height = 3;
    /**
     * <code>required uint32 height = 3;</code>
     */
    boolean hasHeight();
    /**
     * <code>required uint32 height = 3;</code>
     */
    int getHeight();

    // required .photo.img.ImageFormat format = 4;
    /**
     * <code>required .photo.img.ImageFormat format = 4;</code>
     */
    boolean hasFormat();
    /**
     * <code>required .photo.img.ImageFormat format = 4;</code>
     */
    photo.img.ImageDefs.ImageFormat getFormat();

    // required .photo.bki.ImageId imageId = 5;
    /**
     * <code>required .photo.bki.ImageId imageId = 5;</code>
     */
    boolean hasImageId();
    /**
     * <code>required .photo.bki.ImageId imageId = 5;</code>
     */
    photo.bki.ImageBki.ImageId getImageId();
    /**
     * <code>required .photo.bki.ImageId imageId = 5;</code>
     */
    photo.bki.ImageBki.ImageIdOrBuilder getImageIdOrBuilder();

    // required bytes content = 6;
    /**
     * <code>required bytes content = 6;</code>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 6;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code photo.bki.ImageStruct}
   */
  public static final class ImageStruct extends
      com.google.protobuf.GeneratedMessage
      implements ImageStructOrBuilder {
    // Use ImageStruct.newBuilder() to construct.
    private ImageStruct(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ImageStruct(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ImageStruct defaultInstance;
    public static ImageStruct getDefaultInstance() {
      return defaultInstance;
    }

    public ImageStruct getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ImageStruct(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fullUrl_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              width_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              height_ = input.readUInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              photo.img.ImageDefs.ImageFormat value = photo.img.ImageDefs.ImageFormat.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                format_ = value;
              }
              break;
            }
            case 42: {
              photo.bki.ImageBki.ImageId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = imageId_.toBuilder();
              }
              imageId_ = input.readMessage(photo.bki.ImageBki.ImageId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(imageId_);
                imageId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return photo.bki.ImageBki.internal_static_photo_bki_ImageStruct_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return photo.bki.ImageBki.internal_static_photo_bki_ImageStruct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              photo.bki.ImageBki.ImageStruct.class, photo.bki.ImageBki.ImageStruct.Builder.class);
    }

    public static com.google.protobuf.Parser<ImageStruct> PARSER =
        new com.google.protobuf.AbstractParser<ImageStruct>() {
      public ImageStruct parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageStruct(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ImageStruct> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string fullUrl = 1;
    public static final int FULLURL_FIELD_NUMBER = 1;
    private java.lang.Object fullUrl_;
    /**
     * <code>required string fullUrl = 1;</code>
     */
    public boolean hasFullUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fullUrl = 1;</code>
     */
    public java.lang.String getFullUrl() {
      java.lang.Object ref = fullUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fullUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fullUrl = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFullUrlBytes() {
      java.lang.Object ref = fullUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 width = 2;
    public static final int WIDTH_FIELD_NUMBER = 2;
    private int width_;
    /**
     * <code>required uint32 width = 2;</code>
     */
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 width = 2;</code>
     */
    public int getWidth() {
      return width_;
    }

    // required uint32 height = 3;
    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_;
    /**
     * <code>required uint32 height = 3;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 height = 3;</code>
     */
    public int getHeight() {
      return height_;
    }

    // required .photo.img.ImageFormat format = 4;
    public static final int FORMAT_FIELD_NUMBER = 4;
    private photo.img.ImageDefs.ImageFormat format_;
    /**
     * <code>required .photo.img.ImageFormat format = 4;</code>
     */
    public boolean hasFormat() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .photo.img.ImageFormat format = 4;</code>
     */
    public photo.img.ImageDefs.ImageFormat getFormat() {
      return format_;
    }

    // required .photo.bki.ImageId imageId = 5;
    public static final int IMAGEID_FIELD_NUMBER = 5;
    private photo.bki.ImageBki.ImageId imageId_;
    /**
     * <code>required .photo.bki.ImageId imageId = 5;</code>
     */
    public boolean hasImageId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .photo.bki.ImageId imageId = 5;</code>
     */
    public photo.bki.ImageBki.ImageId getImageId() {
      return imageId_;
    }
    /**
     * <code>required .photo.bki.ImageId imageId = 5;</code>
     */
    public photo.bki.ImageBki.ImageIdOrBuilder getImageIdOrBuilder() {
      return imageId_;
    }

    // required bytes content = 6;
    public static final int CONTENT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 6;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes content = 6;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private void initFields() {
      fullUrl_ = "";
      width_ = 0;
      height_ = 0;
      format_ = photo.img.ImageDefs.ImageFormat.IF_JPEG;
      imageId_ = photo.bki.ImageBki.ImageId.getDefaultInstance();
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFullUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFormat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasImageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getImageId().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFullUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, width_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, height_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, format_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, imageId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFullUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, width_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, height_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, format_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, imageId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static photo.bki.ImageBki.ImageStruct parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static photo.bki.ImageBki.ImageStruct parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageStruct parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static photo.bki.ImageBki.ImageStruct parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageStruct parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static photo.bki.ImageBki.ImageStruct parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageStruct parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static photo.bki.ImageBki.ImageStruct parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageStruct parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static photo.bki.ImageBki.ImageStruct parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(photo.bki.ImageBki.ImageStruct prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code photo.bki.ImageStruct}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements photo.bki.ImageBki.ImageStructOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return photo.bki.ImageBki.internal_static_photo_bki_ImageStruct_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return photo.bki.ImageBki.internal_static_photo_bki_ImageStruct_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                photo.bki.ImageBki.ImageStruct.class, photo.bki.ImageBki.ImageStruct.Builder.class);
      }

      // Construct using photo.bki.ImageBki.ImageStruct.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getImageIdFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fullUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        format_ = photo.img.ImageDefs.ImageFormat.IF_JPEG;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (imageIdBuilder_ == null) {
          imageId_ = photo.bki.ImageBki.ImageId.getDefaultInstance();
        } else {
          imageIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return photo.bki.ImageBki.internal_static_photo_bki_ImageStruct_descriptor;
      }

      public photo.bki.ImageBki.ImageStruct getDefaultInstanceForType() {
        return photo.bki.ImageBki.ImageStruct.getDefaultInstance();
      }

      public photo.bki.ImageBki.ImageStruct build() {
        photo.bki.ImageBki.ImageStruct result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public photo.bki.ImageBki.ImageStruct buildPartial() {
        photo.bki.ImageBki.ImageStruct result = new photo.bki.ImageBki.ImageStruct(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fullUrl_ = fullUrl_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.format_ = format_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (imageIdBuilder_ == null) {
          result.imageId_ = imageId_;
        } else {
          result.imageId_ = imageIdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof photo.bki.ImageBki.ImageStruct) {
          return mergeFrom((photo.bki.ImageBki.ImageStruct)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(photo.bki.ImageBki.ImageStruct other) {
        if (other == photo.bki.ImageBki.ImageStruct.getDefaultInstance()) return this;
        if (other.hasFullUrl()) {
          bitField0_ |= 0x00000001;
          fullUrl_ = other.fullUrl_;
          onChanged();
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasFormat()) {
          setFormat(other.getFormat());
        }
        if (other.hasImageId()) {
          mergeImageId(other.getImageId());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFullUrl()) {
          
          return false;
        }
        if (!hasWidth()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        if (!hasFormat()) {
          
          return false;
        }
        if (!hasImageId()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (!getImageId().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        photo.bki.ImageBki.ImageStruct parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (photo.bki.ImageBki.ImageStruct) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string fullUrl = 1;
      private java.lang.Object fullUrl_ = "";
      /**
       * <code>required string fullUrl = 1;</code>
       */
      public boolean hasFullUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fullUrl = 1;</code>
       */
      public java.lang.String getFullUrl() {
        java.lang.Object ref = fullUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fullUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fullUrl = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFullUrlBytes() {
        java.lang.Object ref = fullUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fullUrl = 1;</code>
       */
      public Builder setFullUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fullUrl = 1;</code>
       */
      public Builder clearFullUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fullUrl_ = getDefaultInstance().getFullUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string fullUrl = 1;</code>
       */
      public Builder setFullUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullUrl_ = value;
        onChanged();
        return this;
      }

      // required uint32 width = 2;
      private int width_ ;
      /**
       * <code>required uint32 width = 2;</code>
       */
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 width = 2;</code>
       */
      public int getWidth() {
        return width_;
      }
      /**
       * <code>required uint32 width = 2;</code>
       */
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000002;
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 width = 2;</code>
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        width_ = 0;
        onChanged();
        return this;
      }

      // required uint32 height = 3;
      private int height_ ;
      /**
       * <code>required uint32 height = 3;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 height = 3;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>required uint32 height = 3;</code>
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000004;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 height = 3;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000004);
        height_ = 0;
        onChanged();
        return this;
      }

      // required .photo.img.ImageFormat format = 4;
      private photo.img.ImageDefs.ImageFormat format_ = photo.img.ImageDefs.ImageFormat.IF_JPEG;
      /**
       * <code>required .photo.img.ImageFormat format = 4;</code>
       */
      public boolean hasFormat() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .photo.img.ImageFormat format = 4;</code>
       */
      public photo.img.ImageDefs.ImageFormat getFormat() {
        return format_;
      }
      /**
       * <code>required .photo.img.ImageFormat format = 4;</code>
       */
      public Builder setFormat(photo.img.ImageDefs.ImageFormat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        format_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .photo.img.ImageFormat format = 4;</code>
       */
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000008);
        format_ = photo.img.ImageDefs.ImageFormat.IF_JPEG;
        onChanged();
        return this;
      }

      // required .photo.bki.ImageId imageId = 5;
      private photo.bki.ImageBki.ImageId imageId_ = photo.bki.ImageBki.ImageId.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          photo.bki.ImageBki.ImageId, photo.bki.ImageBki.ImageId.Builder, photo.bki.ImageBki.ImageIdOrBuilder> imageIdBuilder_;
      /**
       * <code>required .photo.bki.ImageId imageId = 5;</code>
       */
      public boolean hasImageId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .photo.bki.ImageId imageId = 5;</code>
       */
      public photo.bki.ImageBki.ImageId getImageId() {
        if (imageIdBuilder_ == null) {
          return imageId_;
        } else {
          return imageIdBuilder_.getMessage();
        }
      }
      /**
       * <code>required .photo.bki.ImageId imageId = 5;</code>
       */
      public Builder setImageId(photo.bki.ImageBki.ImageId value) {
        if (imageIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          imageId_ = value;
          onChanged();
        } else {
          imageIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .photo.bki.ImageId imageId = 5;</code>
       */
      public Builder setImageId(
          photo.bki.ImageBki.ImageId.Builder builderForValue) {
        if (imageIdBuilder_ == null) {
          imageId_ = builderForValue.build();
          onChanged();
        } else {
          imageIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .photo.bki.ImageId imageId = 5;</code>
       */
      public Builder mergeImageId(photo.bki.ImageBki.ImageId value) {
        if (imageIdBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              imageId_ != photo.bki.ImageBki.ImageId.getDefaultInstance()) {
            imageId_ =
              photo.bki.ImageBki.ImageId.newBuilder(imageId_).mergeFrom(value).buildPartial();
          } else {
            imageId_ = value;
          }
          onChanged();
        } else {
          imageIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .photo.bki.ImageId imageId = 5;</code>
       */
      public Builder clearImageId() {
        if (imageIdBuilder_ == null) {
          imageId_ = photo.bki.ImageBki.ImageId.getDefaultInstance();
          onChanged();
        } else {
          imageIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>required .photo.bki.ImageId imageId = 5;</code>
       */
      public photo.bki.ImageBki.ImageId.Builder getImageIdBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getImageIdFieldBuilder().getBuilder();
      }
      /**
       * <code>required .photo.bki.ImageId imageId = 5;</code>
       */
      public photo.bki.ImageBki.ImageIdOrBuilder getImageIdOrBuilder() {
        if (imageIdBuilder_ != null) {
          return imageIdBuilder_.getMessageOrBuilder();
        } else {
          return imageId_;
        }
      }
      /**
       * <code>required .photo.bki.ImageId imageId = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          photo.bki.ImageBki.ImageId, photo.bki.ImageBki.ImageId.Builder, photo.bki.ImageBki.ImageIdOrBuilder> 
          getImageIdFieldBuilder() {
        if (imageIdBuilder_ == null) {
          imageIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              photo.bki.ImageBki.ImageId, photo.bki.ImageBki.ImageId.Builder, photo.bki.ImageBki.ImageIdOrBuilder>(
                  imageId_,
                  getParentForChildren(),
                  isClean());
          imageId_ = null;
        }
        return imageIdBuilder_;
      }

      // required bytes content = 6;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes content = 6;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes content = 6;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>required bytes content = 6;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes content = 6;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:photo.bki.ImageStruct)
    }

    static {
      defaultInstance = new ImageStruct(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:photo.bki.ImageStruct)
  }

  public interface ImageRefOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userId = 1;
    /**
     * <code>required string userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>required string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    // required .photo.bki.SocNet socNet = 2;
    /**
     * <code>required .photo.bki.SocNet socNet = 2;</code>
     */
    boolean hasSocNet();
    /**
     * <code>required .photo.bki.SocNet socNet = 2;</code>
     */
    photo.bki.ImageBki.SocNet getSocNet();

    // optional .photo.bki.ImageId avatarId = 3;
    /**
     * <code>optional .photo.bki.ImageId avatarId = 3;</code>
     */
    boolean hasAvatarId();
    /**
     * <code>optional .photo.bki.ImageId avatarId = 3;</code>
     */
    photo.bki.ImageBki.ImageId getAvatarId();
    /**
     * <code>optional .photo.bki.ImageId avatarId = 3;</code>
     */
    photo.bki.ImageBki.ImageIdOrBuilder getAvatarIdOrBuilder();

    // repeated .photo.bki.ImageId imageIds = 4;
    /**
     * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
     */
    java.util.List<photo.bki.ImageBki.ImageId> 
        getImageIdsList();
    /**
     * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
     */
    photo.bki.ImageBki.ImageId getImageIds(int index);
    /**
     * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
     */
    int getImageIdsCount();
    /**
     * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
     */
    java.util.List<? extends photo.bki.ImageBki.ImageIdOrBuilder> 
        getImageIdsOrBuilderList();
    /**
     * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
     */
    photo.bki.ImageBki.ImageIdOrBuilder getImageIdsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code photo.bki.ImageRef}
   */
  public static final class ImageRef extends
      com.google.protobuf.GeneratedMessage
      implements ImageRefOrBuilder {
    // Use ImageRef.newBuilder() to construct.
    private ImageRef(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ImageRef(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ImageRef defaultInstance;
    public static ImageRef getDefaultInstance() {
      return defaultInstance;
    }

    public ImageRef getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ImageRef(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              photo.bki.ImageBki.SocNet value = photo.bki.ImageBki.SocNet.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                socNet_ = value;
              }
              break;
            }
            case 26: {
              photo.bki.ImageBki.ImageId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = avatarId_.toBuilder();
              }
              avatarId_ = input.readMessage(photo.bki.ImageBki.ImageId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(avatarId_);
                avatarId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                imageIds_ = new java.util.ArrayList<photo.bki.ImageBki.ImageId>();
                mutable_bitField0_ |= 0x00000008;
              }
              imageIds_.add(input.readMessage(photo.bki.ImageBki.ImageId.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          imageIds_ = java.util.Collections.unmodifiableList(imageIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return photo.bki.ImageBki.internal_static_photo_bki_ImageRef_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return photo.bki.ImageBki.internal_static_photo_bki_ImageRef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              photo.bki.ImageBki.ImageRef.class, photo.bki.ImageBki.ImageRef.Builder.class);
    }

    public static com.google.protobuf.Parser<ImageRef> PARSER =
        new com.google.protobuf.AbstractParser<ImageRef>() {
      public ImageRef parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageRef(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ImageRef> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    /**
     * <code>required string userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .photo.bki.SocNet socNet = 2;
    public static final int SOCNET_FIELD_NUMBER = 2;
    private photo.bki.ImageBki.SocNet socNet_;
    /**
     * <code>required .photo.bki.SocNet socNet = 2;</code>
     */
    public boolean hasSocNet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .photo.bki.SocNet socNet = 2;</code>
     */
    public photo.bki.ImageBki.SocNet getSocNet() {
      return socNet_;
    }

    // optional .photo.bki.ImageId avatarId = 3;
    public static final int AVATARID_FIELD_NUMBER = 3;
    private photo.bki.ImageBki.ImageId avatarId_;
    /**
     * <code>optional .photo.bki.ImageId avatarId = 3;</code>
     */
    public boolean hasAvatarId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .photo.bki.ImageId avatarId = 3;</code>
     */
    public photo.bki.ImageBki.ImageId getAvatarId() {
      return avatarId_;
    }
    /**
     * <code>optional .photo.bki.ImageId avatarId = 3;</code>
     */
    public photo.bki.ImageBki.ImageIdOrBuilder getAvatarIdOrBuilder() {
      return avatarId_;
    }

    // repeated .photo.bki.ImageId imageIds = 4;
    public static final int IMAGEIDS_FIELD_NUMBER = 4;
    private java.util.List<photo.bki.ImageBki.ImageId> imageIds_;
    /**
     * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
     */
    public java.util.List<photo.bki.ImageBki.ImageId> getImageIdsList() {
      return imageIds_;
    }
    /**
     * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
     */
    public java.util.List<? extends photo.bki.ImageBki.ImageIdOrBuilder> 
        getImageIdsOrBuilderList() {
      return imageIds_;
    }
    /**
     * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
     */
    public int getImageIdsCount() {
      return imageIds_.size();
    }
    /**
     * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
     */
    public photo.bki.ImageBki.ImageId getImageIds(int index) {
      return imageIds_.get(index);
    }
    /**
     * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
     */
    public photo.bki.ImageBki.ImageIdOrBuilder getImageIdsOrBuilder(
        int index) {
      return imageIds_.get(index);
    }

    private void initFields() {
      userId_ = "";
      socNet_ = photo.bki.ImageBki.SocNet.OK;
      avatarId_ = photo.bki.ImageBki.ImageId.getDefaultInstance();
      imageIds_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSocNet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAvatarId()) {
        if (!getAvatarId().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getImageIdsCount(); i++) {
        if (!getImageIds(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, socNet_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, avatarId_);
      }
      for (int i = 0; i < imageIds_.size(); i++) {
        output.writeMessage(4, imageIds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, socNet_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, avatarId_);
      }
      for (int i = 0; i < imageIds_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, imageIds_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static photo.bki.ImageBki.ImageRef parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static photo.bki.ImageBki.ImageRef parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageRef parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static photo.bki.ImageBki.ImageRef parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageRef parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static photo.bki.ImageBki.ImageRef parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageRef parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static photo.bki.ImageBki.ImageRef parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static photo.bki.ImageBki.ImageRef parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static photo.bki.ImageBki.ImageRef parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(photo.bki.ImageBki.ImageRef prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code photo.bki.ImageRef}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements photo.bki.ImageBki.ImageRefOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return photo.bki.ImageBki.internal_static_photo_bki_ImageRef_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return photo.bki.ImageBki.internal_static_photo_bki_ImageRef_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                photo.bki.ImageBki.ImageRef.class, photo.bki.ImageBki.ImageRef.Builder.class);
      }

      // Construct using photo.bki.ImageBki.ImageRef.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAvatarIdFieldBuilder();
          getImageIdsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        socNet_ = photo.bki.ImageBki.SocNet.OK;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (avatarIdBuilder_ == null) {
          avatarId_ = photo.bki.ImageBki.ImageId.getDefaultInstance();
        } else {
          avatarIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (imageIdsBuilder_ == null) {
          imageIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          imageIdsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return photo.bki.ImageBki.internal_static_photo_bki_ImageRef_descriptor;
      }

      public photo.bki.ImageBki.ImageRef getDefaultInstanceForType() {
        return photo.bki.ImageBki.ImageRef.getDefaultInstance();
      }

      public photo.bki.ImageBki.ImageRef build() {
        photo.bki.ImageBki.ImageRef result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public photo.bki.ImageBki.ImageRef buildPartial() {
        photo.bki.ImageBki.ImageRef result = new photo.bki.ImageBki.ImageRef(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.socNet_ = socNet_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (avatarIdBuilder_ == null) {
          result.avatarId_ = avatarId_;
        } else {
          result.avatarId_ = avatarIdBuilder_.build();
        }
        if (imageIdsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            imageIds_ = java.util.Collections.unmodifiableList(imageIds_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.imageIds_ = imageIds_;
        } else {
          result.imageIds_ = imageIdsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof photo.bki.ImageBki.ImageRef) {
          return mergeFrom((photo.bki.ImageBki.ImageRef)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(photo.bki.ImageBki.ImageRef other) {
        if (other == photo.bki.ImageBki.ImageRef.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          bitField0_ |= 0x00000001;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasSocNet()) {
          setSocNet(other.getSocNet());
        }
        if (other.hasAvatarId()) {
          mergeAvatarId(other.getAvatarId());
        }
        if (imageIdsBuilder_ == null) {
          if (!other.imageIds_.isEmpty()) {
            if (imageIds_.isEmpty()) {
              imageIds_ = other.imageIds_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureImageIdsIsMutable();
              imageIds_.addAll(other.imageIds_);
            }
            onChanged();
          }
        } else {
          if (!other.imageIds_.isEmpty()) {
            if (imageIdsBuilder_.isEmpty()) {
              imageIdsBuilder_.dispose();
              imageIdsBuilder_ = null;
              imageIds_ = other.imageIds_;
              bitField0_ = (bitField0_ & ~0x00000008);
              imageIdsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getImageIdsFieldBuilder() : null;
            } else {
              imageIdsBuilder_.addAllMessages(other.imageIds_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasSocNet()) {
          
          return false;
        }
        if (hasAvatarId()) {
          if (!getAvatarId().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getImageIdsCount(); i++) {
          if (!getImageIds(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        photo.bki.ImageBki.ImageRef parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (photo.bki.ImageBki.ImageRef) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userId = 1;
      private java.lang.Object userId_ = "";
      /**
       * <code>required string userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }

      // required .photo.bki.SocNet socNet = 2;
      private photo.bki.ImageBki.SocNet socNet_ = photo.bki.ImageBki.SocNet.OK;
      /**
       * <code>required .photo.bki.SocNet socNet = 2;</code>
       */
      public boolean hasSocNet() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .photo.bki.SocNet socNet = 2;</code>
       */
      public photo.bki.ImageBki.SocNet getSocNet() {
        return socNet_;
      }
      /**
       * <code>required .photo.bki.SocNet socNet = 2;</code>
       */
      public Builder setSocNet(photo.bki.ImageBki.SocNet value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        socNet_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .photo.bki.SocNet socNet = 2;</code>
       */
      public Builder clearSocNet() {
        bitField0_ = (bitField0_ & ~0x00000002);
        socNet_ = photo.bki.ImageBki.SocNet.OK;
        onChanged();
        return this;
      }

      // optional .photo.bki.ImageId avatarId = 3;
      private photo.bki.ImageBki.ImageId avatarId_ = photo.bki.ImageBki.ImageId.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          photo.bki.ImageBki.ImageId, photo.bki.ImageBki.ImageId.Builder, photo.bki.ImageBki.ImageIdOrBuilder> avatarIdBuilder_;
      /**
       * <code>optional .photo.bki.ImageId avatarId = 3;</code>
       */
      public boolean hasAvatarId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .photo.bki.ImageId avatarId = 3;</code>
       */
      public photo.bki.ImageBki.ImageId getAvatarId() {
        if (avatarIdBuilder_ == null) {
          return avatarId_;
        } else {
          return avatarIdBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .photo.bki.ImageId avatarId = 3;</code>
       */
      public Builder setAvatarId(photo.bki.ImageBki.ImageId value) {
        if (avatarIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          avatarId_ = value;
          onChanged();
        } else {
          avatarIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .photo.bki.ImageId avatarId = 3;</code>
       */
      public Builder setAvatarId(
          photo.bki.ImageBki.ImageId.Builder builderForValue) {
        if (avatarIdBuilder_ == null) {
          avatarId_ = builderForValue.build();
          onChanged();
        } else {
          avatarIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .photo.bki.ImageId avatarId = 3;</code>
       */
      public Builder mergeAvatarId(photo.bki.ImageBki.ImageId value) {
        if (avatarIdBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              avatarId_ != photo.bki.ImageBki.ImageId.getDefaultInstance()) {
            avatarId_ =
              photo.bki.ImageBki.ImageId.newBuilder(avatarId_).mergeFrom(value).buildPartial();
          } else {
            avatarId_ = value;
          }
          onChanged();
        } else {
          avatarIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .photo.bki.ImageId avatarId = 3;</code>
       */
      public Builder clearAvatarId() {
        if (avatarIdBuilder_ == null) {
          avatarId_ = photo.bki.ImageBki.ImageId.getDefaultInstance();
          onChanged();
        } else {
          avatarIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .photo.bki.ImageId avatarId = 3;</code>
       */
      public photo.bki.ImageBki.ImageId.Builder getAvatarIdBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAvatarIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .photo.bki.ImageId avatarId = 3;</code>
       */
      public photo.bki.ImageBki.ImageIdOrBuilder getAvatarIdOrBuilder() {
        if (avatarIdBuilder_ != null) {
          return avatarIdBuilder_.getMessageOrBuilder();
        } else {
          return avatarId_;
        }
      }
      /**
       * <code>optional .photo.bki.ImageId avatarId = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          photo.bki.ImageBki.ImageId, photo.bki.ImageBki.ImageId.Builder, photo.bki.ImageBki.ImageIdOrBuilder> 
          getAvatarIdFieldBuilder() {
        if (avatarIdBuilder_ == null) {
          avatarIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              photo.bki.ImageBki.ImageId, photo.bki.ImageBki.ImageId.Builder, photo.bki.ImageBki.ImageIdOrBuilder>(
                  avatarId_,
                  getParentForChildren(),
                  isClean());
          avatarId_ = null;
        }
        return avatarIdBuilder_;
      }

      // repeated .photo.bki.ImageId imageIds = 4;
      private java.util.List<photo.bki.ImageBki.ImageId> imageIds_ =
        java.util.Collections.emptyList();
      private void ensureImageIdsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          imageIds_ = new java.util.ArrayList<photo.bki.ImageBki.ImageId>(imageIds_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          photo.bki.ImageBki.ImageId, photo.bki.ImageBki.ImageId.Builder, photo.bki.ImageBki.ImageIdOrBuilder> imageIdsBuilder_;

      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public java.util.List<photo.bki.ImageBki.ImageId> getImageIdsList() {
        if (imageIdsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(imageIds_);
        } else {
          return imageIdsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public int getImageIdsCount() {
        if (imageIdsBuilder_ == null) {
          return imageIds_.size();
        } else {
          return imageIdsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public photo.bki.ImageBki.ImageId getImageIds(int index) {
        if (imageIdsBuilder_ == null) {
          return imageIds_.get(index);
        } else {
          return imageIdsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public Builder setImageIds(
          int index, photo.bki.ImageBki.ImageId value) {
        if (imageIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageIdsIsMutable();
          imageIds_.set(index, value);
          onChanged();
        } else {
          imageIdsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public Builder setImageIds(
          int index, photo.bki.ImageBki.ImageId.Builder builderForValue) {
        if (imageIdsBuilder_ == null) {
          ensureImageIdsIsMutable();
          imageIds_.set(index, builderForValue.build());
          onChanged();
        } else {
          imageIdsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public Builder addImageIds(photo.bki.ImageBki.ImageId value) {
        if (imageIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageIdsIsMutable();
          imageIds_.add(value);
          onChanged();
        } else {
          imageIdsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public Builder addImageIds(
          int index, photo.bki.ImageBki.ImageId value) {
        if (imageIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageIdsIsMutable();
          imageIds_.add(index, value);
          onChanged();
        } else {
          imageIdsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public Builder addImageIds(
          photo.bki.ImageBki.ImageId.Builder builderForValue) {
        if (imageIdsBuilder_ == null) {
          ensureImageIdsIsMutable();
          imageIds_.add(builderForValue.build());
          onChanged();
        } else {
          imageIdsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public Builder addImageIds(
          int index, photo.bki.ImageBki.ImageId.Builder builderForValue) {
        if (imageIdsBuilder_ == null) {
          ensureImageIdsIsMutable();
          imageIds_.add(index, builderForValue.build());
          onChanged();
        } else {
          imageIdsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public Builder addAllImageIds(
          java.lang.Iterable<? extends photo.bki.ImageBki.ImageId> values) {
        if (imageIdsBuilder_ == null) {
          ensureImageIdsIsMutable();
          super.addAll(values, imageIds_);
          onChanged();
        } else {
          imageIdsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public Builder clearImageIds() {
        if (imageIdsBuilder_ == null) {
          imageIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          imageIdsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public Builder removeImageIds(int index) {
        if (imageIdsBuilder_ == null) {
          ensureImageIdsIsMutable();
          imageIds_.remove(index);
          onChanged();
        } else {
          imageIdsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public photo.bki.ImageBki.ImageId.Builder getImageIdsBuilder(
          int index) {
        return getImageIdsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public photo.bki.ImageBki.ImageIdOrBuilder getImageIdsOrBuilder(
          int index) {
        if (imageIdsBuilder_ == null) {
          return imageIds_.get(index);  } else {
          return imageIdsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public java.util.List<? extends photo.bki.ImageBki.ImageIdOrBuilder> 
           getImageIdsOrBuilderList() {
        if (imageIdsBuilder_ != null) {
          return imageIdsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(imageIds_);
        }
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public photo.bki.ImageBki.ImageId.Builder addImageIdsBuilder() {
        return getImageIdsFieldBuilder().addBuilder(
            photo.bki.ImageBki.ImageId.getDefaultInstance());
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public photo.bki.ImageBki.ImageId.Builder addImageIdsBuilder(
          int index) {
        return getImageIdsFieldBuilder().addBuilder(
            index, photo.bki.ImageBki.ImageId.getDefaultInstance());
      }
      /**
       * <code>repeated .photo.bki.ImageId imageIds = 4;</code>
       */
      public java.util.List<photo.bki.ImageBki.ImageId.Builder> 
           getImageIdsBuilderList() {
        return getImageIdsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          photo.bki.ImageBki.ImageId, photo.bki.ImageBki.ImageId.Builder, photo.bki.ImageBki.ImageIdOrBuilder> 
          getImageIdsFieldBuilder() {
        if (imageIdsBuilder_ == null) {
          imageIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              photo.bki.ImageBki.ImageId, photo.bki.ImageBki.ImageId.Builder, photo.bki.ImageBki.ImageIdOrBuilder>(
                  imageIds_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          imageIds_ = null;
        }
        return imageIdsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:photo.bki.ImageRef)
    }

    static {
      defaultInstance = new ImageRef(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:photo.bki.ImageRef)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_photo_bki_ImageId_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_photo_bki_ImageId_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_photo_bki_ImageStruct_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_photo_bki_ImageStruct_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_photo_bki_ImageRef_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_photo_bki_ImageRef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tbig.proto\022\tphoto.bki\032\020image_defs.proto" +
      "\"\034\n\007ImageId\022\021\n\timageHash\030\001 \002(\004\"\233\001\n\013Image" +
      "Struct\022\017\n\007fullUrl\030\001 \002(\t\022\r\n\005width\030\002 \002(\r\022\016" +
      "\n\006height\030\003 \002(\r\022&\n\006format\030\004 \002(\0162\026.photo.i" +
      "mg.ImageFormat\022#\n\007imageId\030\005 \002(\0132\022.photo." +
      "bki.ImageId\022\017\n\007content\030\006 \002(\014\"\211\001\n\010ImageRe" +
      "f\022\016\n\006userId\030\001 \002(\t\022!\n\006socNet\030\002 \002(\0162\021.phot" +
      "o.bki.SocNet\022$\n\010avatarId\030\003 \001(\0132\022.photo.b" +
      "ki.ImageId\022$\n\010imageIds\030\004 \003(\0132\022.photo.bki" +
      ".ImageId* \n\006SocNet\022\006\n\002OK\020\000\022\006\n\002VK\020\001\022\006\n\002MM",
      "\020\002B\nB\010ImageBki"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_photo_bki_ImageId_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_photo_bki_ImageId_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_photo_bki_ImageId_descriptor,
              new java.lang.String[] { "ImageHash", });
          internal_static_photo_bki_ImageStruct_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_photo_bki_ImageStruct_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_photo_bki_ImageStruct_descriptor,
              new java.lang.String[] { "FullUrl", "Width", "Height", "Format", "ImageId", "Content", });
          internal_static_photo_bki_ImageRef_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_photo_bki_ImageRef_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_photo_bki_ImageRef_descriptor,
              new java.lang.String[] { "UserId", "SocNet", "AvatarId", "ImageIds", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          photo.img.ImageDefs.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
