# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: big.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import data_readers.pb2_reader.image_defs_pb2 as image__defs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='big.proto',
  package='photo.bki',
  syntax='proto2',
  serialized_pb=_b('\n\tbig.proto\x12\tphoto.bki\x1a\x10image_defs.proto\"\x1c\n\x07ImageId\x12\x11\n\timageHash\x18\x01 \x02(\x04\"\x9b\x01\n\x0bImageStruct\x12\x0f\n\x07\x66ullUrl\x18\x01 \x02(\t\x12\r\n\x05width\x18\x02 \x02(\r\x12\x0e\n\x06height\x18\x03 \x02(\r\x12&\n\x06\x66ormat\x18\x04 \x02(\x0e\x32\x16.photo.img.ImageFormat\x12#\n\x07imageId\x18\x05 \x02(\x0b\x32\x12.photo.bki.ImageId\x12\x0f\n\x07\x63ontent\x18\x06 \x02(\x0c\"\x89\x01\n\x08ImageRef\x12\x0e\n\x06userId\x18\x01 \x02(\t\x12!\n\x06socNet\x18\x02 \x02(\x0e\x32\x11.photo.bki.SocNet\x12$\n\x08\x61vatarId\x18\x03 \x01(\x0b\x32\x12.photo.bki.ImageId\x12$\n\x08imageIds\x18\x04 \x03(\x0b\x32\x12.photo.bki.ImageId* \n\x06SocNet\x12\x06\n\x02OK\x10\x00\x12\x06\n\x02VK\x10\x01\x12\x06\n\x02MM\x10\x02\x42\nB\x08ImageBki')
  ,
  dependencies=[image__defs__pb2.DESCRIPTOR,])

_SOCNET = _descriptor.EnumDescriptor(
  name='SocNet',
  full_name='photo.bki.SocNet',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MM', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=370,
  serialized_end=402,
)
_sym_db.RegisterEnumDescriptor(_SOCNET)

SocNet = enum_type_wrapper.EnumTypeWrapper(_SOCNET)
OK = 0
VK = 1
MM = 2



_IMAGEID = _descriptor.Descriptor(
  name='ImageId',
  full_name='photo.bki.ImageId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageHash', full_name='photo.bki.ImageId.imageHash', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=70,
)


_IMAGESTRUCT = _descriptor.Descriptor(
  name='ImageStruct',
  full_name='photo.bki.ImageStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fullUrl', full_name='photo.bki.ImageStruct.fullUrl', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='photo.bki.ImageStruct.width', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='photo.bki.ImageStruct.height', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='photo.bki.ImageStruct.format', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageId', full_name='photo.bki.ImageStruct.imageId', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='photo.bki.ImageStruct.content', index=5,
      number=6, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=228,
)


_IMAGEREF = _descriptor.Descriptor(
  name='ImageRef',
  full_name='photo.bki.ImageRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='photo.bki.ImageRef.userId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='socNet', full_name='photo.bki.ImageRef.socNet', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avatarId', full_name='photo.bki.ImageRef.avatarId', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageIds', full_name='photo.bki.ImageRef.imageIds', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=368,
)

_IMAGESTRUCT.fields_by_name['format'].enum_type = image__defs__pb2._IMAGEFORMAT
_IMAGESTRUCT.fields_by_name['imageId'].message_type = _IMAGEID
_IMAGEREF.fields_by_name['socNet'].enum_type = _SOCNET
_IMAGEREF.fields_by_name['avatarId'].message_type = _IMAGEID
_IMAGEREF.fields_by_name['imageIds'].message_type = _IMAGEID
DESCRIPTOR.message_types_by_name['ImageId'] = _IMAGEID
DESCRIPTOR.message_types_by_name['ImageStruct'] = _IMAGESTRUCT
DESCRIPTOR.message_types_by_name['ImageRef'] = _IMAGEREF
DESCRIPTOR.enum_types_by_name['SocNet'] = _SOCNET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageId = _reflection.GeneratedProtocolMessageType('ImageId', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEID,
  __module__ = 'big_pb2'
  # @@protoc_insertion_point(class_scope:photo.bki.ImageId)
  ))
_sym_db.RegisterMessage(ImageId)

ImageStruct = _reflection.GeneratedProtocolMessageType('ImageStruct', (_message.Message,), dict(
  DESCRIPTOR = _IMAGESTRUCT,
  __module__ = 'big_pb2'
  # @@protoc_insertion_point(class_scope:photo.bki.ImageStruct)
  ))
_sym_db.RegisterMessage(ImageStruct)

ImageRef = _reflection.GeneratedProtocolMessageType('ImageRef', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEREF,
  __module__ = 'big_pb2'
  # @@protoc_insertion_point(class_scope:photo.bki.ImageRef)
  ))
_sym_db.RegisterMessage(ImageRef)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\010ImageBki'))
# @@protoc_insertion_point(module_scope)
