# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_defs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_defs.proto',
  package='photo.img',
  syntax='proto2',
  serialized_pb=_b('\n\x10image_defs.proto\x12\tphoto.img*s\n\x0bImageFormat\x12\x0b\n\x07IF_JPEG\x10\x00\x12\n\n\x06IF_PNG\x10\x01\x12\n\n\x06IF_GIF\x10\x02\x12\x0e\n\nIF_UNKNOWN\x10\x03\x12\n\n\x06IF_ICO\x10\x04\x12\n\n\x06IF_BMP\x10\x05\x12\x0b\n\x07IF_WEBP\x10\x06\x12\n\n\x06IF_SVG\x10\x07\x42\x0b\x42\tImageDefs')
)

_IMAGEFORMAT = _descriptor.EnumDescriptor(
  name='ImageFormat',
  full_name='photo.img.ImageFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IF_JPEG', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IF_PNG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IF_GIF', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IF_UNKNOWN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IF_ICO', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IF_BMP', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IF_WEBP', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IF_SVG', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=31,
  serialized_end=146,
)
_sym_db.RegisterEnumDescriptor(_IMAGEFORMAT)

ImageFormat = enum_type_wrapper.EnumTypeWrapper(_IMAGEFORMAT)
IF_JPEG = 0
IF_PNG = 1
IF_GIF = 2
IF_UNKNOWN = 3
IF_ICO = 4
IF_BMP = 5
IF_WEBP = 6
IF_SVG = 7


DESCRIPTOR.enum_types_by_name['ImageFormat'] = _IMAGEFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\tImageDefs'))
# @@protoc_insertion_point(module_scope)
